const sampleNotePresets = {
    physics: `Maxwell's equations represent one of the most elegant syntheses in physics:
1. Gauss's Law: Electric flux through a closed surface is proportional to enclosed charge (div E = rho / epsilon_0).
2. Gauss's Law for Magnetism: There are no magnetic monopoles (div B = 0).
3. Faraday's Law of Induction: A changing magnetic flux induces an electromotive force (curl E = -dB/dt).
4. Ampere-Maxwell Law: Magnetic fields are generated by electric currents and time-varying electric displacement (curl B = mu_0 * J + mu_0 * epsilon_0 * dE/dt).`,
    biology: `DNA replication is a semiconservative biological process in which two identical replicas are synthesized from a single original DNA molecule:
- Helicase unwinds the double helix at replication forks.
- Single-Stranded Binding Proteins (SSBs) stabilize template strands.
- RNA Primase synthesizes short RNA primers to provide a 3'-OH group.
- DNA Polymerase III extends the leading strand continuously 5'->3' and lagging strand discontinuously into Okazaki fragments.
- DNA Ligase seals phosphodiester nicks.`,
    cs: `Dynamic Programming is an algorithmic technique for solving optimization problems by breaking them down into overlapping subproblems with optimal substructure:
1. Memoization (Top-Down): Cache intermediate recursive results in a hash table or array.
2. Tabulation (Bottom-Up): Iteratively solve base cases first and fill a state transition table.
Common examples: 0/1 Knapsack Problem, Longest Common Subsequence (LCS), Bellman-Ford shortest paths.`
};

function setNotePreset(presetKey) {
    if (noteInput && sampleNotePresets[presetKey]) {
        noteInput.value = sampleNotePresets[presetKey];
        window.showToast(`Loaded ${presetKey.toUpperCase()} sample notes!`, "info");
    }
}

window.setNotePreset = setNotePreset;

const output = document.getElementById("output-card");
const historyList = document.getElementById("history-list");
const noteInput = document.getElementById("note-input");
const fileInput = document.getElementById("file-upload");
const copyOutputBtn = document.getElementById("copy-output-btn");
const exportDocBtn = document.getElementById("export-notes-doc-btn");
const clearInputBtn = document.getElementById("clear-input-btn");
const modeButtons = document.querySelectorAll(".action-btn");

let currentExplanationMarkdown = "";

/* Save and update history */
function saveHistory(item) {
    try {
        let list = JSON.parse(localStorage.getItem("expHistory") || "[]");
        list.unshift({
            id: Date.now(),
            title: item.title || item.input.slice(0, 40) + "...",
            input: item.input,
            output: item.output,
            type: item.type,
            date: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        });
        if (list.length > 8) list.pop();
        localStorage.setItem("expHistory", JSON.stringify(list));
    } catch (e) {
        console.error("Storage error:", e);
    }
}

function updateHistory() {
    if (!historyList) return;
    try {
        let list = JSON.parse(localStorage.getItem("expHistory") || "[]");
        if (list.length === 0) {
            historyList.innerHTML = `<div class="empty-history">No previous notes syntheses yet. Select a mode above to begin!</div>`;
            return;
        }

        historyList.innerHTML = list.map((item, idx) => `
            <div class="history-item" data-index="${idx}">
                <div class="history-meta">
                    <span class="history-tag">${item.type || 'Explain'}</span>
                    <span class="history-time">${item.date || ''}</span>
                </div>
                <div class="history-preview">${item.title}</div>
            </div>
        `).join("");

        // Attach click listeners to restore from history
        document.querySelectorAll(".history-item").forEach(el => {
            el.addEventListener("click", () => {
                const idx = el.getAttribute("data-index");
                const item = list[idx];
                if (item) {
                    if (noteInput) noteInput.value = item.input;
                    currentExplanationMarkdown = item.output;
                    if (output) {
                        output.innerHTML = window.renderMarkdown(item.output);
                        output.scrollIntoView({ behavior: "smooth" });
                    }
                    if (copyOutputBtn) copyOutputBtn.style.display = "inline-flex";
                    if (exportDocBtn) exportDocBtn.style.display = "inline-flex";
                    window.showToast("Restored from history", "info");
                }
            });
        });
    } catch (e) {
        console.error("Failed to load history:", e);
    }
}

/* File Upload Reader */
if (fileInput) {
    fileInput.addEventListener("change", (e) => {
        const file = e.target.files[0];
        if (!file) return;

        const reader = new FileReader();
        reader.onload = (event) => {
            if (noteInput) {
                noteInput.value = event.target.result;
                window.showToast(`Loaded file: ${file.name}`, "success");
            }
        };
        reader.onerror = () => {
            window.showToast("Failed to read file", "error");
        };

        reader.readAsText(file);
    });
}

/* Clear Input */
if (clearInputBtn) {
    clearInputBtn.addEventListener("click", () => {
        if (noteInput) {
            noteInput.value = "";
            noteInput.focus();
            window.showToast("Input cleared", "info");
        }
    });
}

/* Copy Output */
if (copyOutputBtn) {
    copyOutputBtn.addEventListener("click", () => {
        if (!currentExplanationMarkdown) return;
        navigator.clipboard.writeText(currentExplanationMarkdown).then(() => {
            window.showToast("Copied to clipboard!", "success");
        }).catch(() => {
            window.showToast("Failed to copy text", "error");
        });
    });
}

/* Export DOC */
if (exportDocBtn) {
    exportDocBtn.addEventListener("click", () => {
        if (!currentExplanationMarkdown) return;
        const header = `<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
        <head><meta charset='utf-8'><title>Study Notes</title>
        <style>body { font-family: 'Segoe UI', Arial, sans-serif; line-height: 1.6; color: #222; } table { border-collapse: collapse; width: 100%; } td, th { border: 1px solid #ccc; padding: 8px; }</style>
        </head><body>`;
        const footer = `</body></html>`;
        const htmlContent = header + window.renderMarkdown(currentExplanationMarkdown) + footer;

        const blob = new Blob(['\ufeff' + htmlContent], {
            type: 'application/msword;charset=utf-8'
        });

        const link = document.createElement("a");
        link.href = URL.createObjectURL(blob);
        link.download = "AI-StudyFlow-Notes.doc";
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        window.showToast("Downloaded DOC successfully!", "success");
    });
}

/* Main AI Execution Handler */
async function runExplain(type) {
    const input = noteInput ? noteInput.value.trim() : "";
    if (!input) {
        window.showToast("Please paste or type your notes first!", "warning");
        if (noteInput) noteInput.focus();
        return;
    }

    // Highlight active mode button
    modeButtons.forEach(btn => {
        if (btn.getAttribute("onclick")?.includes(type)) {
            btn.classList.add("active-mode");
        } else {
            btn.classList.remove("active-mode");
        }
    });

    const modeLabels = {
        cornell: "Cornell Notes Format",
        cheatsheet: "1-Page Cheat Sheet",
        solve: "Step-by-Step Problem Solver",
        simplify: "ELI5 Concept Simplifier",
        summarize: "Executive Academic Summary",
        questions: "Exam Practice Questions"
    };

    output.innerHTML = `
        <div class="loading-state">
            <div class="spinner"></div>
            <p class="loading-text">AI is synthesizing notes in <strong>${modeLabels[type] || type.toUpperCase()}</strong> mode...</p>
        </div>
    `;
    if (copyOutputBtn) copyOutputBtn.style.display = "none";
    if (exportDocBtn) exportDocBtn.style.display = "none";

    try {
        const result = await window.apiFetch("explain", {
            text: input,
            type: type
        });

        currentExplanationMarkdown = result;
        output.innerHTML = window.renderMarkdown(result);
        if (copyOutputBtn) copyOutputBtn.style.display = "inline-flex";
        if (exportDocBtn) exportDocBtn.style.display = "inline-flex";

        saveHistory({
            input: input,
            output: result,
            type: modeLabels[type] || type,
            title: input.slice(0, 50) + (input.length > 50 ? "..." : "")
        });
        updateHistory();
        window.showToast("Notes processed successfully!", "success");

        output.scrollIntoView({ behavior: "smooth", block: "nearest" });

    } catch (err) {
        console.error("Explainer request error:", err);
        output.innerHTML = `
            <div class="error-box">
                <h3>⚠️ Processing Error</h3>
                <p>${err.message || "Could not reach server. Please ensure the backend is running."}</p>
                <button class="mini-btn" onclick="runExplain('${type}')">🔄 Retry</button>
            </div>
        `;
        window.showToast("Failed to analyze notes. Check backend server.", "error");
    }
}

// Attach globally
window.runExplain = runExplain;

// Initialize on page load
document.addEventListener("DOMContentLoaded", () => {
    updateHistory();
});
